project:
  type: website

website:
  navbar:
    right:
      - text: About
        href: index.qmd
      - text: Posts
        href: blog.qmd
      - text: Presentations
        href: presentations.qmd
    left: 
      - text: Eli Kravitz 
format:
  html:
    theme:
      light: sandstone
      dark: cyborg

editor: visual

